version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - sudo yum install -y docker
      - sudo docker start  # start Docker service
      - sudo docker --version  # Verify Docker installation
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - sudo $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 235494789667.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Building the Docker image...
      - sudo docker build -t springboot-app .
      - sudo docker tag springboot-app:latest 235494789667.dkr.ecr.us-east-1.amazonaws.com/springboot-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - sudo docker push 235494789667.dkr.ecr.us-east-1.amazonaws.com/springboot-app:latest

artifacts:
  files:
    - '**/*'
